---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/carts/{cart_id}/cart_items":
    parameters:
    - name: product_id
      in: query
      description: ID of the product
      required: true
      schema:
        type: integer
    - name: cart_id
      in: path
      description: ID of the cart_item
      required: true
      schema:
        type: integer
    post:
      summary: create cart_item
      tags:
      - CartItems
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/cart_item"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/cart_item"
  "/api/v1/carts/{cart_id}/cart_items/{id}":
    parameters:
    - name: product_id
      in: query
      description: ID of the product
      required: true
      schema:
        type: integer
    - name: cart_id
      in: path
      description: ID of the cart_item
      required: true
      schema:
        type: integer
    - name: id
      in: path
      description: ID of the cart_item
      required: true
      schema:
        type: integer
    get:
      summary: show cart_item
      tags:
      - CartItems
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    patch:
      summary: update cart_lines
      tags:
      - CartItems
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/cart_item"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/cart_item"
    delete:
      summary: delete cart_lines
      tags:
      - CartItems
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
  "/api/v1/carts":
    get:
      summary: list carts
      tags:
      - Carts
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    post:
      summary: create cart
      tags:
      - Carts
      security:
      - Bearer: []
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/cart"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/cart"
  "/api/v1/carts/{id}":
    parameters:
    - name: id
      in: path
      description: ID of the cart
      required: true
      schema:
        type: integer
    get:
      summary: show cart
      tags:
      - Carts
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    patch:
      summary: update cart
      tags:
      - Carts
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/cart"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/cart"
  "/api/v1/categories":
    get:
      summary: list categories
      tags:
      - Categories
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
      - Categories
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/category"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/category"
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Categories
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/category"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/category"
    delete:
      summary: delete category
      tags:
      - Categories
      responses:
        '200':
          description: successful
  "/api/v1/categories/{category_id}/products":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: integer
    get:
      summary: show category products list
      tags:
      - Products
      responses:
        '200':
          description: successful
    post:
      summary: create product in category
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: product created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/product"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/product"
  "/api/v1/password_update":
    post:
      summary: password update
      tags:
      - Passwords
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: successful
        '406':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/password_update"
  "/api/v1/products":
    get:
      summary: list products
      tags:
      - Products
      responses:
        '200':
          description: successful
    post:
      summary: create product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: product created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/product"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/product"
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show product
      tags:
      - Products
      responses:
        '200':
          description: successful
    patch:
      summary: update product
      tags:
      - Products
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/product"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/product"
    delete:
      summary: delete product
      tags:
      - Products
      responses:
        '200':
          description: successful
  "/api/v1/login":
    post:
      summary: login
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/session"
  "/api/v1/users/all":
    get:
      summary: list users
      tags:
      - Users
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
  "/api/v1/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/user_response"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/user"
    get:
      summary: show user
      tags:
      - Users
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - Users
      security:
      - Bearer: []
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/user_response"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/user"
    delete:
      summary: delete user
      tags:
      - Users
      security:
      - Bearer: []
      responses:
        '200':
          description: successful
servers:
- url: https://{bookStoreHost}
  variables:
    bookStoreHost:
      default: book-store-api-tc-5855f695cf77.herokuapp.com
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
components:
  schemas:
    category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        meta_title:
          type: string
          nullable: true
        meta_description:
          type: string
          nullable: true
      required:
      - name
    product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        meta_title:
          type: string
          nullable: true
        meta_description:
          type: string
          nullable: true
        price:
          type: integer
          default: 0
        quantity:
          type: integer
          default: 0
        category_id:
          type: integer
        status:
          type: string
          enum:
          - active
          - inactive
          - archived
          default: active
      required:
      - name
      - description
    cart:
      type: object
      properties:
        status:
          type: string
          enum:
          - unpaid
          - paid
          - canceled
          default: unpaid
    cart_item:
      type: object
      properties:
        quantity:
          type: integer
          default: 0
        price:
          type: float
          default: 0.0
    user:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
      - first_name
      - last_name
      - email
      - password
    user_response:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
        token:
          type: string
        expires:
          type: string
    session:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
      - email
      - password
    password_update:
      type: object
      properties:
        old_password:
          type: string
        password:
          type: string
      required:
      - old_password
      - password
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      name: Authorization
      in: header
      description: Your Bearer token
