---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    get:
      summary: list products
      tags:
      - Products
      responses:
        '200':
          description: successful
    post:
      summary: create product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: product created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/product"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/product"
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show product
      tags:
      - Products
      responses:
        '200':
          description: successful
    patch:
      summary: update product
      tags:
      - Products
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/product"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/product"
    delete:
      summary: delete product
      tags:
      - Products
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/user"
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/user"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/user"
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '200':
          description: successful
servers:
- url: https://{bookStoreHost}
  variables:
    defaultHost:
      default: book-store-api-tc-5855f695cf77.herokuapp.com
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
components:
  schemas:
    product:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        meta_title:
          type: string
          nullable: true
        meta_description:
          type: string
          nullable: true
        price:
          type: integer
          default: 0
        quantity:
          type: integer
          default: 0
        status:
          type: string
          enum:
          - active
          - inactive
          - archived
          default: active
      required:
      - name
      - description
    user:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        password:
          type: string
      required:
      - first_name
      - last_name
      - email
      - password
