development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_store_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_store_test

production:
  adapter: redis
  url: redis://default:mqHrNVFFMwrHc2exnrp4kHBXBAIOTe92@redis-15818.c3.eu-west-1-1.ec2.cloud.redislabs.com:15818
  channel_prefix: book_store_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
