development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_store_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: book_store_test

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:REDISCLOUD_URL) { "redis://localhost:6379/1" } %>
  channel_prefix: book_store_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
