
:scheduler:
  :schedule:
    subsciption_bestseller:
      cron: "* * * * * *"   # Runs once per minute
      class: "Email::SubscriptionBestsellerWorker"
      queue: "default"
      description: "Run service to subscriptions people once per mounth"
