:concurrency: 5
:queues:
  - default

:max_retries: 1

:scheduler:
  :schedule:
    email_subsciption_bestseller:
      cron: '* * * * * *'   # Runs once per minute
      class: Email::SubscriptionBestsellerWorker